import Head from "next/head";
import { useSession } from "next-auth/react";
import Header from "../components/Header";

export default function Home() {
  const { data: session, status } = useSession();
  const loading = status === "loading";

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-red-700">
        <Header />
      </main>
    </div>
  );
}
